name = "marv3"
account_id = "e1fc4922f78222b947a9c549529329aa"
main = "api/src/worker.ts"
compatibility_date = "2024-05-13"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "siematap.xyz/api/*", zone_name = "siematap.xyz" }
]
workers_dev = true

[vars]
VECTOR_TOP_K = "8"
CHUNK_SIZE = "1500"
CHUNK_OVERLAP = "200"
OPENAI_MODEL = "gpt-5-mini-2025-08-07"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"

[[d1_databases]]
binding = "MARBLE_DB"
database_name = "marv3_db"
database_id = "f48ac66f-6a89-42b1-ae83-da464216c47a"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MARBLE_FILES"
bucket_name = "marv3-files"

[[vectorize]]
binding = "MARBLE_VECTORS"
index_name = "marv3-index"

[observability.logs]
enabled = true
